### PR TITLE
Add iOS build support

### PR DESCRIPTION
**Pull request by Kudo**
- [x] Merge Android/iOS build scripts to universal scripts
- [x] Find CI support

### CODE REVIEW

**Comment by akshetpandey** [comment]
@Kudo : You can use Bitrise for macos build env.

**Comment by Kudo** [comment]
@akshetpandey I am trying GitHub Actions CI now. Do you have any comments for GitHub v.s. Bitrise?

**Comment by akshetpandey** [comment]
I haven't used github, I have used bitrise extensively and it works pretty well...

**Comment by Kudo** [comment]
Well, please let me try GitHub first, will try Bitrise if I am getting failure.

**Comment by Kudo** [comment]
GitHub CI passed and original Android CircleCI works well too.
I am going to merge this into master.

**Pull request merged**
